# Generated by Django 5.1.1 on 2024-09-16 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('mark', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=4)),
                ('di_nmb', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
                ('pupils', models.CharField(max_length=4)),
            ],
        ),
    ]
